### PR TITLE
Create build for .NET SDK to 7 preview 3

### PR DESCRIPTION
**Pull request by StachuDotNet**

### CODE REVIEW

**Comment by pbiggar** [comment]
I'll merge this now. If we end up not merging the PR on the dark repo, we'll need to revert or overwrite when we next update. That's fine, just being explicit.

**Comment by StachuDotNet** [comment]
Thanks!

> If we end up not merging the PR on the dark repo, we'll need to revert or overwrite when we next update.

Why? Does something "pull from latest?" I was under the impression that the resultant images were always referenced by SHA1

**Comment by pbiggar** [comment]
Nothing pulls from latest. Just a matter of not confusing ourselves, or basing future changes off the wrong version.

**Comment by StachuDotNet** [comment]
Given [the decision](https://github.com/darklang/dark/pull/3730#issuecomment-1111038115) to not move forward with .NET 7 yet, should be done here?

> we'll need to revert or overwrite when we next update

Would you like additional commits to revert, or 'delete' the commits?

**Comment by pbiggar** [comment]
Yeah, I think worth reverting to the latest we have deployed.

**Pull request merged**
